version: 2
checks:
  method-complexity:
    config:
      threshold: 10
plugins:
  brakeman:
    enabled: true
    checks:
      csrf_not_protected_by_raising_exception:
        enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-54
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
exclude_patterns:
  - config/**/*
  - db/**/*
  - spec/**/*
  - vendor/**/*
  - "**/__generated__/**/*"
