#!/bin/bash
set -x

case "$SUITE" in
  rspec)
    bin/rake db:create db:test:prepare
    bin/rspec
    ;;
  browser)
    bin/rake assets:precompile
    bin/rake db:create db:test:prepare
    bin/rspec -t browser
    ;;
  yarn)
    bin/yarn
    bin/webpack
    bin/yarn test
    bin/yarn codecov
    ;;
  *)
    echo "Please set the SUITE env var"
    ;;
esac
